global:
  scrape_interval: 15s
  evaluation_interval: 15s


scrape_configs:
  - job_name: 'prometheus_master'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'jenkins'
    static_configs:
    - targets: ['localhost:8080']
    metrics_path: '/prometheus/'
